---
title: "Books and Resources for 431"
---

### The Book you need to purchase

During the course, we will read David Spiegelhalter's **The Art of Statistics**, which was first published by Penguin in March 2019 (and February 2020) in the UK and then by Basic Books in the US in September 2019. You can purchase any of the available versions (hard-cover, paperback or e-reader) online or in your local bookstore for about $20.

- [Dr. Spiegelhalter's website](http://www.statslab.cam.ac.uk/~david/) has lots of useful information.
- The [book's website](https://dspiegel29.github.io/ArtofStatistics/) contains R code, corrections and other materials.
- You are welcome to read this book before class starts, if you'd like to get a jump on things, but that's not necessary: we'll link readings to the syllabus when that becomes available.

Everything else that you will need is free, and will be described in detail on the main course website once the class begins. Some highlights follow...

### Three Books you should download at your next opportunity

There are three additional **free** books that you will definitely need to obtain during the semester and may be interested in looking at before class begins. Simply visit the links below.

1. [Introduction to Modern Statistics](https://openintro-ims.netlify.app/) by Mine Cetinkaya-Rundel and Johanna Hardin.
2. [R for Data Science](https://r4ds.had.co.nz/) by Garrett Grolemund and Hadley Wickham.
3. [Biostatistics for Biomedical Research](http://hbiostat.org/doc/bbr.pdf) (pdf) by Frank E. Harrell Jr and James C Slaughter. This is regularly updated by the authors, as indicated on [their course website](https://hbiostat.org/bbr/), so get the most recent version occasionally.

### Professor Love's Materials will be available when class begins

Dr. Love has a set of Notes for the course, titled **Data Science for Biological, Medical and Health Research: Notes for PQHS 431.** 

- A link to the current draft of these notes will be provided at the first class session. The notes are permanently a work in progress, and updates occur irregularly throughout the semester.
- Although these Notes share some of the features of a textbook, they are neither comprehensive nor completely original. The main purpose is to give 431 students a set of common materials on which to draw during the course, providing a series of examples using R to work through issues that are likely to come up during the semester, and in later work.  

In addition, **slides** and video recordings from each of Professor Love's lectures, plus other in-class materials from each session of the class will be posted in a timely fashion on the main course website.

