---
title: "Enrolling in 431-432"
---

## You must register and enroll in the course

Your first step is to register and enroll in the course via the [CWRU Student Information System (SIS)](https://sis.case.edu/). All students who wish to take the course must submit a request for enrollment prior to the first class via SIS.

### There are three "flavors" of 431. 

- If you are a student in the Clinical Research Scholars Certificate, MS or PhD program, register for CRSP 431.
- If you are a student in the Masters of Public Health program, you will want to register for MPHP 431.
- All other students, including non-degree students, should register for PQHS 431.

### The class will fill. 

Some people who want to take the course will **not** be able to enroll this year. The class size is restricted to 55 students.

- While some students (based on their degree program) will be admitted immediately, others will be placed on a waiting list, which we will review on 2021-08-17 and continue to review until 2021-08-23, when final decisions will be made. 
- If you have been placed on the waiting list, please feel free to write a short email to Dr. Love if you are interested in letting him know more about your situation. Students planning to take both 431 and 432 in the 2021-22 cycle will receive higher priority than students planning only to take 431.

### Special Circumstances

- Dr. Love does not allow students to audit his courses, nor does he allow students to take his courses pass-fail.
- Dr. Love does allow students in degree programs where the course would be an overload to take 431 (and 432) as a fellowship course.
- Students in the PQHS department wishing to waive 431 should discuss that with their advisor and with Dr. Love, and should consider whether serving as a [volunteer teaching assistant](http://bit.ly/ta-positions-431-2021) would be in their best interest.

If you have any questions, please contact Dr. Love at the email address below.