---
title: "Questions (and Answers) About 431-432"
---

## How do I get help?

Before the class begins, contact Dr. Love at the email address on the bottom of this page with any questions. 

- Our first class is August 23. At that class, we'll describe all of the ways we have for you to get help during the semester. 

### Do I have to be in Cleveland to take this course?

Yes. 431 is an in-class experience. You will need to be in Room E321-323 in the Robbins Building of the CWRU School of Medicine on Tuesdays and Thursdays from 1:00 to 2:15 PM to take the course. We will comply, of course, with all University requirements.

### Will all class materials be available to me online?

No, but many things will be available. All slides and many other materials will be provided after each class, but in-class attendance is required. 

### Will the class have teaching assistants and office hours?

Yes, it will. Most of this Fall's TAs are students who took this course one or two years ago. Some are volunteering their time to help you understand this stuff better. All office hours and all teaching assistant work will be done remotely.

### How do I get connected to Zoom through CWRU?

By now, you're probably familiar with Zoom. You should review [the CWRU Knowledge Base for Zoom](https://case.edu/utech/help/knowledge-base/zoom/zoom-information) prior to our first class to set up a CWRU Zoom account. The course sessions will not be delivered on Zoom, but office hours and some other activities will use Zoom.

### What if I get sick, or have to care for someone who is sick once the semester starts?

In general, we ask students to contact Dr. Love directly (method will be specified at the first class) when you encounter any problem which will keep you from participating in the course for **more than two sessions in a row** to figure out what sort of accommodations will be needed.

### Can I audit 431 or 432?

No. Enrolled students and teaching assistants are the only people permitted to attend the course.

### Is it possible to take the course pass/fail?

No, it is not. However, no student in the past five years has received a final course grade other than A, B or Incomplete.

### How will I know how I'm doing in the class?

We aim for substantial and timely feedback from the teaching assistants and myself on all elements of the course.

### If I take 431, do I have to also take 432 in the Spring?

It is the natural thing to do. The 431 course is part 1 of a two-semester sequence. Frankly, 432 contains some of the most interesting material and is generally regarded by students who take both as the more entertaining course. Every year, some students take only 431, though. The decision is up to you. The 432 course assumes you have completed 431.

### What should I be doing before class to get ready?

Take a look at the list [we've provided here](index.html), and also try to get some rest. It will be a busy semester.

### More to come...

More questions (and answers) will appear here as needed in response to student emails sent to the address below, and in response to your comments on the [Welcome to 431 Survey](https://bit.ly/431-2021-welcome-survey).
